export const CERTIFICATION_TERMS_VERSION = "2026-04-15";
export const CERTIFICATION_TERMS_EFFECTIVE_DATE = CERTIFICATION_TERMS_VERSION;
export const CERTIFICATION_TERMS_PATH = "/certifications/terms";
